<!doctype html>
<html lang="en">


    <head>
         <meta charset="utf-8">
         <meta name="viewport" content="width=device-width, initial-scale=1">
         <title>Receita de bolo</title>
         <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
         <link rel="stylesheet" href="/resources/demos/style.css">
	     <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
         <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
        <script>
           $( function() {
           $( "#accordion" ).accordion();
        } );
        </script>
		<script type="text/javascript">
	     $(document).ready(function() {
			 alert("Vamos fazer um bolo!");
		 });
	</script>
	<style type="text/css">
		    .linha {
		       font-weight: bold;
			   color: Blue;
			   padding-left: 20px;
			   line-height: 20px
		    }
		</style>
    </head>
	
    <body>
         
	
        <div id="accordion">
              <h3>Ingredientes</h3>
              <div>
            <p>
			<ul>
              <li><span class=\Linha\>2 xícaras (chá) de açúcar</span class></li>
              <li>3 xícaras (chá) de farinha de trigo</li>
              <li>4 colheres (sopa) de margarina</li>
              <li>3 ovos</li>
              <li>1 e 1/2 xícara (chá) de leite</li>
              <li>1 colher (sopa) bem cheia de fermento em pó</li>
			</ul>
            </p>
        </div>
         <h3>MODO DE PREPARO </h3>
        <div>
            <p>
              <li>Bata as claras em neve e reserve.</li>
              <li>Misture as gemas, a margarina e o açúcar até obter uma massa homogênea.</li>
              <li>Acrescente o leite e a farinha de trigo aos poucos, sem parar de bater.</li>
              <li>Por último, adicione as claras em neve e o fermento.</li>
              <li>Despeje a massa em uma forma grande de furo central untada e enfarinhada.</li>
              <li>Asse em forno médio 180 °C, preaquecido, por aproximadamente 40 minutos ou ao furar o bolo com um garfo, este saia limpo.</li>
            </p>
        </div>
          <h3>INFORMAÇÕES ADICIONAIS</h3>
        <div>
            <p>
              Sabe o que combina com essa receita? Um delicioso cappuccino caseiro!

             Você sabia que seus bolos podem ficar ainda mais gostosos se acompanhados de uma receita de chocolate quente? 
			 
			 Que tal fazer essa combinação deliciosa? A gente jura que você vai amar! 
            </p>
      
        </div>
 
 
    </body>

</html>